
'''
1. Remove the spaces from both the end for the strings: first, second, parent, city 
2. Capitalize the first letter for the strings: first, second, parent 
3. Print the strings first, second, parent and city separated by space. 
4. Check if the string phone contains only numerical characters and print the result (True or False) 
5. Check if the phone number starts with the value in string start and print the result (True or False) 
6. Print Total number of times the string strfind appears in the strings (first, second, parent, city) 
7. Print the list generated by using the split function on string1.(Hint: Use split() function) 
8. Find the position of string strfind in the city. (Hint: Use find() function)
'''

#!/bin/python3

import math
import os
import random
import re
import sys



#
# Complete the 'resume' function below.
#
# The function is expected to print a STRING.
# The function accepts following parameters:
#  1. STRING first
#  2. STRING second
#  3. STRING parent
#  4. STRING city
#  5. STRING phone
#  6. STRING start
#  7. STRING strfind
#  8. STRING string1
#

def remove_space(s):
    return s.strip()

def counting(substr, *args):
    count = 0
    for item in args:
        count += item.count(substr)
    return count

def resume(first, second, parent, city, phone, start, strfind, string1):
    first = remove_space(first).capitalize()
    second = remove_space(second).capitalize()
    parent = remove_space(parent).capitalize()
    city = remove_space(city)

    print(f"{first} {second} {parent} {city}")
    print(phone.isnumeric())
    print(phone.startswith(start))
    print(counting(strfind, first, second, parent, city))
    print(string1.split())
    print(city.find(strfind))

    
if __name__ == '__main__':

    a = input()

    b = input()

    c = input()

    d = input()

    ph = input()

    no = input()

    ch = input()

    str = input()

    resume(a, b, c, d, ph, no, ch, str)

